#!/usr/bin/env python
# -*- coding: utf-8 -*-
# pylint: disable=R0801

DEFAULT_ALLOCATOR_URI = 'http://bbpcd013.bbp.epfl.ch/nip'
DEFAULT_ALLOCATOR_NAME = 'rendering-resource-manager'
DEFAULT_ALLOCATOR_API_VERSION = 'v1'
DEFAULT_ALLOCATOR_SESSION_PREFIX = 'session'
DEFAULT_ALLOCATOR_CONFIG_PREFIX = 'config'
DEFAULT_ALLOCATOR_NB_NODES = 1
DEFAULT_ALLOCATOR_NB_CPUS = 1
DEFAULT_ALLOCATOR_NB_GPUS = 0
DEFAULT_ALLOCATOR_TIME = '1:00:00'
DEFAULT_ALLOCATOR_EXCLUSIVE = False
DEFAULT_RENDERER = 'bbic_image_converter_2'
SESSION_MAX_CONNECTION_ATTEMPTS = 5
